### creating numpy arrays

In [1]:
import numpy as np

In [3]:
np.array(range(0, 5))

# can create a range from a list like object

array([0, 1, 2, 3, 4])

In [6]:
# Notice that unlike a python list 
# everything must be of the same type 

numbers = list(range(0, 5))
numbers.append('not a number')
numbers

[0, 1, 2, 3, 4, 'not a number']

In [10]:
np_nums = np.array(range(0, 4))

In [11]:
np_nums.dtype

dtype('int64')

In [13]:
updated = np.append(np_nums, 3)

array([0, 1, 2, 3, 3])

In [14]:
attempt = np.append(np_nums, 'ok')

In [19]:
attempt[0]

### this coerces everything to a string

'0'

### Seeding arrays, and arrays of multiple dimensions

In [27]:
np.random.randint(1, 10, size = 3)

array([7, 5, 9])

In [30]:
np.random.randint(1, 10, size = 3)

array([9, 4, 9])

In [31]:
np.random.seed(3)

In [32]:
np.random.randint(1, 10, size =3)

array([9, 4, 9])

In [33]:
np.random.randint(1, 10, size =3)

array([9, 1, 6])

In [34]:
np.random.seed(3)

In [35]:
np.random.randint(1, 10, size =3)

array([9, 4, 9])

In [38]:
np.random.randint(1, 10, size=(3, 4, 2))

array([[[5, 2],
        [3, 3],
        [5, 9],
        [1, 7]],

       [[1, 5],
        [2, 6],
        [2, 9],
        [9, 8]],

       [[1, 1],
        [2, 8],
        [9, 8],
        [5, 1]]])

In [44]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [45]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [84]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [85]:
np.full((2, 2), 4)

array([[4, 4],
       [4, 4]])

### Changing arrays

Split, Stack, Concatenate

In [52]:
odds = np.arange(1, 10, 2)
odds

array([1, 3, 5, 7, 9])

In [53]:
evens = np.arange(0, 9, 2)

In [55]:
np.concatenate([odds, evens])

array([1, 3, 5, 7, 9, 0, 2, 4, 6, 8])

In [57]:
all_nums = np.array([odds, evens])

In [58]:
all_nums

array([[1, 3, 5, 7, 9],
       [0, 2, 4, 6, 8]])

In [74]:
np.split(together, [1, 2])

[array([1]), array([3]), array([5, 7, 9, 0, 2, 4, 6, 8])]

In [75]:
np.vsplit(all_nums, 2)

[array([[1, 3, 5, 7, 9]]), array([[0, 2, 4, 6, 8]])]

In [78]:
np.hsplit(all_nums, [4])

[array([[1, 3, 5, 7],
        [0, 2, 4, 6]]), array([[9],
        [8]])]

In [79]:
together = np.concatenate(all_nums, axis=0)